# Generated by Django 2.2.12 on 2020-09-30 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_users', to=settings.AUTH_USER_MODEL, verbose_name='즐겨찾기한 사람들'),
        ),
    ]
