# Generated by Django 2.2.12 on 2020-11-17 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20201113_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to=settings.AUTH_USER_MODEL, verbose_name='찜(즐겨찾기)한 사람들'),
        ),
    ]
