# Generated by Django 2.2.12 on 2020-11-18 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_auto_20201118_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite_count',
        ),
    ]
