# Generated by Django 2.2.12 on 2020-11-18 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_post_favorite_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '창업정보 게시물', 'verbose_name_plural': '창업정보 게시물'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '댓글(창업정보 게시물의 댓글)', 'verbose_name_plural': '댓글(창업정보 게시물의 댓글)'},
        ),
    ]
