# Generated by Django 2.2.12 on 2020-11-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_auto_20201119_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('view_count', models.CharField(max_length=16, verbose_name='조회수')),
                ('url', models.URLField(verbose_name='링크')),
                ('created_at', models.CharField(max_length=16, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '창업넷 공지사항(공공데이터)',
                'verbose_name_plural': '창업넷 공지사항(공공데이터)',
            },
        ),
    ]
