# Generated by Django 2.2.12 on 2020-11-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_publicpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicpost',
            name='view_count',
        ),
    ]
