# Generated by Django 2.2.12 on 2020-12-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_remove_publicpost_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
