# Generated by Django 2.2.12 on 2020-12-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_user_login_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_id',
        ),
    ]
