# Generated by Django 2.2.12 on 2020-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20201215_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartUpPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('enterprise', models.CharField(max_length=128, verbose_name='기업')),
                ('address', models.CharField(max_length=128, verbose_name='주소')),
                ('tel', models.CharField(max_length=128, verbose_name='연락처')),
                ('latitude', models.IntegerField(verbose_name='위도')),
                ('longitude', models.IntegerField(verbose_name='경도')),
                ('created_at', models.CharField(max_length=16, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '창업공간',
                'verbose_name_plural': '창업공간',
            },
        ),
    ]
