# Generated by Django 2.2.12 on 2020-12-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_startupplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupplace',
            name='created_at',
        ),
    ]
