# Generated by Django 2.2.12 on 2020-12-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20201215_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupplace',
            name='tel',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='연락처'),
        ),
    ]
