# Generated by Django 2.2.12 on 2020-12-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0025_auto_20201215_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupplace',
            name='region',
            field=models.CharField(max_length=32, null=True, verbose_name='지역'),
        ),
    ]
