# Generated by Django 2.2.12 on 2020-12-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_startupplace_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupplace',
            options={'verbose_name': '창업지원센터(공공데이터)', 'verbose_name_plural': '창업지원센터(공공데이터)'},
        ),
    ]
